### ISSUE TITLE
Don't use "magic values" for differentiation

### ISSUE THREAD

**Issue by ribasushi** [jplindstrom/p5-DBIx-Class-BatchUpdate#1]
This is a [really fragile way of approaching this](https://metacpan.org/source/DBIx::Class::BatchUpdate::Update#L41-42). Imagine someone writing an unpacked version of everything on CPAN to a database and comes across the source of your module. OOOOOPS.

Instead use a [proper serializer](https://github.com/dbsrgits/dbix-class/blob/current/blead/lib/DBIx/Class/_Util.pm#L124-L127) which will account for undefs, and any other weird shit out there (however do not use the module I linked - it's [internal with no API guarantees](https://github.com/dbsrgits/dbix-class/blob/current/blead/lib/DBIx/Class/_Util.pm#L1-L2))

**Comment by ribasushi** [comment]
P.S. good idea otherwise, ++ ;)

**Comment by jplindstrom** [comment]
Fair point. The difference between inhouse code and "software".

Will fix tomorrow.

**Comment by ribasushi** [comment]
Your [current fix](https://metacpan.org/source/JOHANL/DBIx-Class-BatchUpdate-1.002/lib/DBIx/Class/BatchUpdate/Update.pm#L49-63) is fine, but from a performance perspective just producing a raw Storable::nfreeze across the entire bag of values will be much cheaper than what you implemented.

Just a followup thought, functionality-wise the problem is resolved.

**Comment by ribasushi** [comment]
Actually I misread - what is `$_` expected to be set to [here](https://metacpan.org/source/JOHANL/DBIx-Class-BatchUpdate-1.002/lib/DBIx/Class/BatchUpdate/Update.pm#L63)?

**Comment by jplindstrom** [comment]
Good catch, that's bad form. It happens to work in this particular case so the test passed :)

But since I'll have to touch it again I'll just replace it with nfreeze. Initially I wouldn't trust its representation to be stable, but now I see it's specifically mentioned in the docs.

**Comment by ribasushi** [comment]
Right, it's guaranteed stable on **the same version of Storable.pm** as long as you set `local $Storable::canonical = 1;`.

Across various perl/Storable versions the stability is a different story, but that's not a concern in your case.

Cheers!
