### ISSUE TITLE
Dangerous assumption of immutable PK

### ISSUE THREAD

**Issue by ribasushi** [jplindstrom/p5-DBIx-Class-BatchUpdate#3]
Sorry that I didn't notice this the first time around. [This](http://metacpan.org/release/JOHANL/DBIx-Class-BatchUpdate-1.002) is not... ideal. What you want to do is to fall back to the original one-by-one update() logic when any part of the PK (which could be multicolumn) is dirty. Perhaps with a warning (_yada-yada BatchUpdate ineffective_).

Doing anything else is likely to result in bugs that will be extraordinarily hard to diagnose.

**Comment by jplindstrom** [comment]
If the PK is dirty, then it will be included in the batch_key, so that would lead to individual updates.

This approach doesn't at all work with multi-col PKs since it's a simple -in clause. What's the simplest way to detect that the PK isn't a single column?

**Comment by jplindstrom** [comment]
Ahh, I see, if the PK has changed, then it wouldn't be matched in the where clause.

**Comment by ribasushi** [comment]
> Ahh, I see, if the PK has changed, then it wouldn't be matched in the where clause.

Precisely! DBIC internally has ways to deal with this, hence it'd be easiest to just "fall through back to DBIC".

> What's the simplest way to detect that the PK isn't a single column?

You basically loop through `...->result_source->primary_columns` which gives you a list of names to avoid.

**Comment by jplindstrom** [comment]
I don't have the time to spend right now to fix this in a solid way so I'm going to pull a MySQL and document the caveats.

**Comment by jplindstrom** [comment]
Documented and checks for dirty pk values.

This is not a case where you'd randomly update the PK and it works but slowly. You'd want to know.

And if you update the PK for all rows, BatchUpdate wouldn't work anyway.
